from app.services.Book.Book import create_book



def create_sample_books():
    for book in books:
        create_book(book)


books = ({"ISBN": "0312278497",
          "Title": "The Glass Bead Game",
          "Publish_Year": "1970",
          "Summary": "The state of Castalia is the home of an austere order of intellectuals.",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Herman",
          "Author_Last_Name_1": "Hesse",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Picador",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "fantasy"},

         {"ISBN": "0061002828",
          "Title": "The Hellbound Heart",
          "Publish_Year": "1991",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Clive",
          "Author_Last_Name_1": "Barker",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "HarperTorch",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "horror"},

         {"ISBN": "0061091464",
          "Title": "The Thief of Always",
          "Publish_Year": "1993",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Clive",
          "Author_Last_Name_1": "Barker",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "HarperCollins",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "horror"},

         {"ISBN": "9780590120418",
          "Title": "What Was I Scared Of?",
          "Publish_Year": "1997",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Dr.",
          "Author_Last_Name_1": "Seuss",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Scholastic",
          "Owned": "no",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "children"},

         {"ISBN": "1234567890123",
          "Title": "TEST BOOK",
          "Publish_Year": "1997",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Dr.",
          "Author_Last_Name_1": "Seuss",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Scholastic",
          "Owned": "no",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "children"}
         )



if __name__ == '__main__':
    pass