# GenreID: 'Genre'

def genres_for_table():
    genre_table = {1:   'fiction',
                   2:   'nonfiction',
                   110: 'speculative fiction',
                   111: 'fantasy',
                   112: 'science fiction',
                   113: 'horror',
                   114: 'historical fiction',
                   115: 'dystopian',
                   120: 'mystery',
                   121: 'detective',
                   130: 'romance',
                   140: 'action',
                   141: 'adventure',
                   150: 'paranormal',
                   160: 'literature',
                   161: 'classic',
                   162: 'postmodern',
                   190: 'baby',
                   191: 'children',
                   192: 'young adult',
                   200: 'legend',
                   201: 'epic',
                   202: 'myth',
                   203: 'folklore',
                   204: 'fairy tale',
                   301: 'magic',
                   302: 'suspense',
                   303: 'crime',
                   304: 'philosophy',
                   305: 'drama',
                   306: 'humor',
                   307: 'thriller',
                   308: 'animals',
                   309: 'coming-of-age',
                   310: 'military',
                   311: 'realist',
                   401: 'education',
                   402: 'religion',
                   410: 'wellness',
                   411: 'self-help',
                   412: 'cooking',
                   413: 'exercise',
                   420: 'science',
                   421: 'biology',
                   422: 'chemistry',
                   423: 'physics',
                   424: 'programming',
                   425: 'math',
                   430: 'language',
                   440: 'business',
                   450: 'art',
                   451: 'film',
                   452: 'music',
                   453: 'design',
                   454: 'photography',
                   455: 'dance',
                   456: 'painting',
                   460: 'history',
                   461: 'anthropology',
                   462: 'archaeology',
                   470: 'politics',
                   480: 'geography',
                   490: 'psychology',
                   500: 'novel',
                   501: 'novella',
                   502: 'short-stories',
                   503: 'poetry',
                   504: 'play',
                   505: 'essay',
                   506: 'autobiography',
                   507: 'biography',
                   508: 'textbook',
                   509: 'comic',
                   510: 'graphic-novel',
                   511: 'manga',
                   512: 'cookbook',
                   513: 'anthology',
                   514: 'picture book',
                   }
    return genre_table

if __name__ == '__main__':
    pass