# path="/workspaces/Book-Tracker/app/services/"
# Christopher O'Brien
books = ({"ISBN": 749397055,
	  "Title": "The Name of the Rose",
          "Publish_Year": "1922",
	  "Summary": "It is the year 1327. Franciscans in an Italian abbey are suspected of heresy, but Brother William of Baskerville’s investigation is suddenly overshadowed by seven bizarre deaths.",
	  "Chapters":"",
	  "Chapters_Completed":"",
          "Cover_Image":"",
	  "Author_First_Name_1":"Umberto",
	  "Author_Last_Name_1":"Enco",
	  "Author_First_Name_2":"",
	  "Author_Last_Name_2":"",
	  "Publisher_Name": "Secker & Warburg",
	  "Owned":"yes",
	  "Favorite":"no",
	  "Completed":"no",
	  "Currently_Reading":"no",
	  "Personal_Or_Academic":"personal",
	  "Genre_1":"history",
	  "Genre_2":"mystery"},

	{"ISBN":553840010,
	  "Title":"The Alienist",
          "Publish_Year":1995,
	  "Summary": "The year is 1896, the place, New York City. On a cold March night New York Times reporter John Schuyler Moore is summoned to the East River by his friend and former Harvard classmate Dr. Laszlo Kreizler, a psychologist, or "alienist." On the unfinished Williamsburg Bridge, they view the horribly mutilated body of an adolescent boy, a prostitute from one of Manhattan's infamous brothels. The newly appointed police commissioner",
	  "Chapters":"",
	  "Chapters_Completed":"",
          "Cover_Image":"",
	  "Author_First_Name_1":"Caleb",
	  "Author_Last_Name_1":"Carr",
	  "Author_First_Name_2":"",
	  "Author_Last_Name_2":"",
	  "Publisher_Name":"Brantom Books",
	  "Owned":"yes",
	  "Favorite":"no",
	  "Completed":"no",
	  "Currently_Reading":"no",
	  "Personal_Or_Academic":"personal",
	  "Genre_1":"history",
	  "Genre_2":"mystery"},

	{"ISBN":1841979120,
	  "Title":"Dissolution",
          "Publish_Year":2003,
	  "Summary":"Dissolution follows lawyer‑monk Matthew Shardlake as he investigates a brutal murder at a monastery during Henry VIII’s dissolution of the religious houses, uncovering corruption, fear, and political intrigue. His search for the killer forces him to confront the moral collapse of the era and the cost of loyalty in a world reshaped by power.",
	  "Chapters":"",
	  "Chapters_Completed":"",
          "Cover_Image":"",
	  "Author_First_Name_1":"C.J.",
	  "Author_Last_Name_1":"Sansom",
	  "Author_First_Name_2":"",
	  "Author_Last_Name_2":"",
	  "Publisher_Name":"W.F.Howes",
	  "Owned":"yes",
	  "Favorite":"no",
	  "Completed":"no",
	  "Currently_Reading":"no",
	  "Personal_Or_Academic":"personal",
	  "Genre_1": "history",
	  "Genre_2": "mystery"},

	{"ISBN":9780749008529,
	  "Title":"The Beekeeper's Apprentice",
          "Publish_Year":2017,
	  "Summary":"In 1915, Sherlock Holmes is retired and quietly engaged in the study of honeybees in Sussex when a young woman literally stumbles onto him on the Sussex Downs.",
	  "Chapters":"",
	  "Chapters_Completed":"",
          "Cover_Image":"",
	  "Author_First_Name_1":"Laurie",
	  "Author_Last_Name_1":"King",
	  "Author_First_Name_2":"",
	  "Author_Last_Name_2":"",
	  "Publisher_Name":"Allison & Busby",
	  "Owned":"yes",
	  "Favorite":"no",
	  "Completed":"no",
	  "Currently_Reading":"no",
	  "Personal_Or_Academic":"personal",
	  "Genre_1":"mystery",
	  "Genre_2":"history"},

	{"ISBN":753826852,
	  "Title":"The Shadow of the Wind",
          "Publish_Year":2009,
	  "Summary":"Hidden in the heart of the old city of Barcelona is the 'Cemetery of Forgotten Books', a labyrinthine library of obscure and forgotten titles. To this library, a man brings his ten-year-old son, Daniel, one cold morning in 1945.",
	  "Chapters":"",
	  "Chapters_Completed":"",
          "Cover_Image":"",
	  "Author_First_Name_1":"Carlos",
	  "Author_Last_Name_1":"Zafon",
	  "Author_First_Name_2":"",
	  "Author_Last_Name_2":"",
	  "Publisher_Name":"Phoenix",
	  "Owned":"yes",
	  "Favorite":"no",
	  "Completed":"no",
	  "Currently_Reading":"no",
	  "Personal_Or_Academic":"personal",
	  "Genre_1":"mystery",
	  "Genre_2":"history"},

	{"ISBN":1423108752,
	  "Title":"Uncharted: a Gates family mystery",
          "Publish_Year":2008,
	  "Summary":"Follows teenage siblings Nick and Maddie Gates as they uncover a hidden map left by their ancestors, pulling them into a centuries‑old puzzle tied to American history. Their hunt for the truth forces them to outsmart rivals and confront the legacy of the Gates family’s long connection to secret treasures.",
	  "Chapters":"",
	  "Chapters_Completed":"",
          "Cover_Image":"",
	  "Author_First_Name_1":"Cathy",
	  "Author_Last_Name_1":"Hapka",
	  "Author_First_Name_2":"",
	  "Author_Last_Name_2":"",
	  "Publisher_Name":"Disney Press (Hyperion)",
	  "Owned":"yes",
	  "Favorite":"no",
	  "Completed":"no",
	  "Currently_Reading":"no",
	  "Personal_Or_Academic":"personal",
	  "Genre_1":"mystery",
	  "Genre_2":"history"},

	{"ISBN":9781585478927,
	  "Title":"The Thirteenth Tale (Readers Circle (Center Point))",
          "Publish_Year":2007,
	  "Summary":"Who summons a young biographer to hear the true, haunting story of her childhood after a lifetime of fabrications. As the biographer uncovers the dark secrets of the Angelfield family, both women are forced to confront the ghosts—literal and emotional—that have shaped their lives.",
	  "Chapters":"",
	  "Chapters_Completed":"",
          "Cover_Image":"",
	  "Author_First_Name_1":"Diane",
	  "Author_Last_Name_1":"Setterfield",
	  "Author_First_Name_2":"",
	  "Author_Last_Name_2":"",
	  "Publisher_Name":"Center Point Large Print",
	  "Owned":"yes",
	  "Favorite":"no",
	  "Completed":"no",
	  "Currently_Reading":"no",
	  "Personal_Or_Academic":"personal",
	  "Genre_1":"mystery",
	  "Genre_2":"history"}

	{"ISBN":054774501X,
	  "Title":"The Hangman's Daughter",
          "Publish_Year":2011,
	  "Summary":"Germany, 1659: When a dying boy is pulled from the river with a mark crudely tattooed on his shoulder, hangman Jakob Kuisl is called upon to investigate whether witchcraft is at play in his small Bavarian town. Whispers and dark memories of witch trials and the women burned at stake just seventy years earlier still haunt the streets of Schongau.",
	  "Chapters":"",
	  "Chapters_Completed":"",
          "Cover_Image":"",
	  "Author_First_Name_1":"Oliver",
	  "Author_Last_Name_1":"Potzsch",
	  "Author_First_Name_2":"",
	  "Author_Last_Name_2":"",
	  "Publisher_Name":"Houghton Mifflin Harcourt",
	  "Owned":"yes",
	  "Favorite":"no",
	  "Completed":"no",
	  "Currently_Reading":"no",
	  "Personal_Or_Academic":"personal",
	  "Genre_1": "mystery",
	  "Genre_2": "history"},

	{"ISBN": 2310147,
	  "Title": "The ABC Murders",
          "Publish_Year":1967,
	  "Summary":"There's a serial killer on the loose, bent on working his way though the alphabet. There seems little chance of the murderer being caught - until her makes the crucial and vain mistake of challenging Hercule Poirot to frustrate his plans . . .",
	  "Chapters":"",
	  "Chapters_Completed":"",
          "Cover_Image":"",
	  "Author_First_Name_1":"Agatha",
	  "Author_Last_Name_1":"Christie",
	  "Author_First_Name_2":"",
	  "Author_Last_Name_2":"",
	  "Publisher_Name":"Dodd, Meod & Co.",
	  "Owned":"yes",
	  "Favorite":"no",
	  "Completed":"",
	  "Currently_Reading":"no",
	  "Personal_Or_Academic":"personal",
	  "Genre_1":"mystery",
	  "Genre_2":"history"},

	{"ISBN":1401891551,
	  "Title":"Introduction to Health Care",
          "Publish_Year":2006,
	  "Summary":"Understand the different options when it comes to care.  Primary/Emergency/Specialist/!Satellite!",
	  "Chapters":"",
	  "Chapters_Completed":"",
          "Cover_Image":"",
	  "Author_First_Name_1":"Joyce",
	  "Author_Last_Name_1": "Mitchell",
	  "Author_First_Name_2":"Lee",
	  "Author_Last_Name_2": "Haroun",
	  "Publisher_Name":"Cengage Delmar Learning",
	  "Owned":"yes",
	  "Favorite":"no",
	  "Completed":"no",
	  "Currently_Reading":"no",
	  "Personal_Or_Academic":"personal",
	  "Genre_1": "mystery",
	  "Genre_2": "history"}} 
