from app.services.Book.Book import create_book


def create_sample_books():
    for book in books:
        create_book(book)


books = ({"ISBN": "0312278497",
          "Title": "The Glass Bead Game",
          "Publish_Year": "1970",
          "Summary": "The state of Castalia is the home of an austere order of intellectuals.",
          "Chapters": "23",
          "Chapters_Completed": "2",
          "Cover_Image": "",
          "Author_First_Name_1": "Herman",
          "Author_Last_Name_1": "Hesse",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Picador",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "fantasy"},

         {"ISBN": "0061002828",
          "Title": "The Hellbound Heart",
          "Publish_Year": "1991",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Clive",
          "Author_Last_Name_1": "Barker",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "HarperTorch",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "horror"},

         {"ISBN": "0061091464",
          "Title": "The Thief of Always",
          "Publish_Year": "1993",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Clive",
          "Author_Last_Name_1": "Barker",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "HarperCollins",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "horror"},

         {"ISBN": "9780590120418",
          "Title": "What Was I Scared Of?",
          "Publish_Year": "1997",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Dr.",
          "Author_Last_Name_1": "Seuss",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Scholastic",
          "Owned": "no",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "children"},

         {"ISBN": "1234567890123",
          "Title": "TEST BOOK",
          "Publish_Year": "1997",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Dr.",
          "Author_Last_Name_1": "Seuss",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Scholastic",
          "Owned": "no",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "children"},

         {"ISBN": "9781407135397",
          "Title": "The Hunger Games",
          "Publish_Year": "2008",
          "Summary": "",
          "Chapters": "0",
          "Chapters_Completed": "24",
          "Cover_Image": "",
          "Author_First_Name_1": "Suzanne",
          "Author_Last_Name_1": "Collins",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Scholastic",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "science fiction",
          "Genre_3": "dystopian",
          "Genre_4": "children"},

         {"ISBN": "0345421396",
          "Title": "Lucifer's Hammer",
          "Publish_Year": "1998",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Larry",
          "Author_Last_Name_1": "Niven",
          "Author_First_Name_2": "Jerry",
          "Author_Last_Name_2": "Pournelle",
          "Publisher_Name": " Ballantine",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "science fiction"},

         {"ISBN": "9780671434038",
          "Title": "Mote In Gods Eye",
          "Publish_Year": "1981",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Larry",
          "Author_Last_Name_1": "Niven",
          "Author_First_Name_2": "Jerry",
          "Author_Last_Name_2": "Pournelle",
          "Publisher_Name": "Simon and Schuster",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "science fiction"},

{"ISBN": "1529370515",
        "Title": "The Stand",
        "Publish_Year": "1992",
        "Summary": "One man escapes from a biological weapon facility after an accident, carrying with him the deadly virus known as Captain Tripps.",
        "Chapters": "50",
        "Chapters_Completed": "50",
        "Cover_Image": "",
        "Author_First_Name_1": "Stephen",
        "Author_Last_Name_1": "King",
        "Author_First_Name_2": "",
        "Author_Last_Name_2": "",
        "Publisher_Name": "Hodder",
        "Owned": "yes",
        "Favorite": "yes",
        "Completed": "yes",
        "Currently_Reading": "no",
        "Personal_Or_Academic": "personal",
        "Genre_1": "fiction",
        "Genre_2": "horror"},

{"ISBN": "9780425037843",
        "Title": "Pale Fire",
        "Publish_Year": "1977",
        "Summary": "A 999 line poem in heroic couplets, divided into 4 cantos, was composed--according to Nabokov's fiction--by John Francis Shade, an obsessively methodical man, during the last 20 days of his life. ",
        "Chapters": "3",
        "Chapters_Completed": "2",
        "Cover_Image": "",
        "Author_First_Name_1": "Vladimir",
        "Author_Last_Name_1": "Nabokov",
        "Author_First_Name_2": "",
        "Author_Last_Name_2": "",
        "Publisher_Name": "Berkley",
        "Owned": "yes",
        "Favorite": "yes",
        "Completed": "no",
        "Currently_Reading": "yes",
        "Personal_Or_Academic": "personal",
        "Genre_1": "fiction",
        "Genre_2": "literature"},

{"ISBN": "9780425127933",
        "Title": "The Damnation Game",
        "Publish_Year": "1985",
        "Summary": "",
        "Chapters": "30",
        "Chapters_Completed": "20",
        "Cover_Image": "",
        "Author_First_Name_1": "Clive",
        "Author_Last_Name_1": "Barker",
        "Author_First_Name_2": "",
        "Author_Last_Name_2": "",
        "Publisher_Name": "Berkley",
        "Owned": "yes",
        "Favorite": "yes",
        "Completed": "yes",
        "Currently_Reading": "no",
        "Personal_Or_Academic": "personal",
        "Genre_1": "fiction",
        "Genre_2": "horror"},

{"ISBN": "9780201835953",
        "Title": "The Mythical Man-Month",
        "Publish_Year": "1975",
        "Summary": "",
        "Chapters": "30",
        "Chapters_Completed": "20",
        "Cover_Image": "",
        "Author_First_Name_1": "Frederick",
        "Author_Last_Name_1": "Brooks",
        "Author_First_Name_2": "",
        "Author_Last_Name_2": "",
        "Publisher_Name": "Addison-Wesley Professional",
        "Owned": "no",
        "Favorite": "no",
        "Completed": "no",
        "Currently_Reading": "no",
        "Personal_Or_Academic": "academic",
        "Genre_1": "nonfiction",
        "Genre_2": "programming"},

{"ISBN": "0201485370",
        "Title": "Design patterns",
        "Publish_Year": "1995",
        "Summary": "",
        "Chapters": "30",
        "Chapters_Completed": "0",
        "Cover_Image": "",
        "Author_First_Name_1": "Erich",
        "Author_Last_Name_1": "Gamma",
        "Author_First_Name_2": "Richard",
        "Author_Last_Name_2": "Helm",
        "Publisher_Name": "Addison-Wesley Professional",
        "Owned": "no",
        "Favorite": "no",
        "Completed": "no",
        "Currently_Reading": "no",
        "Personal_Or_Academic": "academic",
        "Genre_1": "nonfiction",
        "Genre_2": "programming"},

{"ISBN": "0201485370",
        "Title": "Harry Potter and the Sorcerer's Stone",
        "Publish_Year": "1997",
        "Summary": "",
        "Chapters": "30",
        "Chapters_Completed": "0",
        "Cover_Image": "",
        "Author_First_Name_1": "J.K.",
        "Author_Last_Name_1": "Rowling",
        "Author_First_Name_2": "",
        "Author_Last_Name_2": "",
        "Publisher_Name": "Scholastic ",
        "Owned": "yes",
        "Favorite": "no",
        "Completed": "yes",
        "Currently_Reading": "no",
        "Personal_Or_Academic": "personal",
        "Genre_1": "fiction",
        "Genre_2": "fantasy"},
         )

if __name__ == '__main__':
    pass
