# Sample books for Task 5.5

# Book 1
{"ISBN": "9780345368935",
"Title": "All The Weyrs Of Pern",
"Publish_Year": "1991",
"Summary": "The end of Thread.",
"Chapters": "20",
"Chapters_Completed": "20",
"Cover_Image": "",
"Author_First_Name_1": "Anne",
"Author_Last_Name_1": "McCaffrey",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "Del Rey Books",
"Owned": "yes",
"Favorite": "yes",
"Completed": "yes",
"Currently_Reading": "no",
"Personal_Or_Academic": "personal",
"Genre_1": "fiction",
"Genre_2": "fantasy",
"Genre_3": "science fiction"}

# Book 2
{"ISBN": "0345434692",
"Title": "The Skies Of Pern",
"Publish_Year": "2001",
"Summary": "The last book of the Dragonriders of Pern series.",
"Chapters": "4",
"Chapters_Completed": "4",
"Cover_Image": "",
"Author_First_Name_1": "Anne",
"Author_Last_Name_1": "McCaffrey",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "Del Rey Books",
"Owned": "yes",
"Favorite": "yes",
"Completed": "yes",
"Currently_Reading": "no",
"Personal_Or_Academic": "personal",
"Genre_1": "fiction",
"Genre_2": "fantasy",
"Genre_3": "science fiction"}

# Book 3
{"ISBN": "9780345484260",
"Title": "Dragonflight",
"Publish_Year": "2005",
"Summary": "The first book of the Dragonriders of Pern series.",
"Chapters": "4",
"Chapters_Completed": "4",
"Cover_Image": "",
"Author_First_Name_1": "Anne",
"Author_Last_Name_1": "McCaffrey",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "Del Rey Books",
"Owned": "yes",
"Favorite": "no",
"Completed": "yes",
"Currently_Reading": "no",
"Personal_Or_Academic": "personal",
"Genre_1": "fiction",
"Genre_2": "fantasy",
"Genre_3": "science fiction"}

# Book 4
{"ISBN": "0764568825",
"Title": "Taming the Flame",
"Publish_Year": "2005",
"Summary": "Secrets for Hot-and-Quick Grilling and Low-and-Slow BBQ",
"Chapters": "",
"Chapters_Completed": "",
"Cover_Image": "",
"Author_First_Name_1": "Elizabeth",
"Author_Last_Name_1": "Karmel",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "Wiley Publishing Inc",
"Owned": "yes",
"Favorite": "no",
"Completed": "no",
"Currently_Reading": "no",
"Personal_Or_Academic": "personal",
"Genre_1": "nonfiction",
"Genre_2": "cookbook"}

# Book 5
{"ISBN": "0553274295",
"Title": "Where The Red Fern Grows",
"Publish_Year": "2001",
"Summary": "",
"Chapters": "",
"Chapters_Completed": "",
"Cover_Image": "",
"Author_First_Name_1": "Wilson",
"Author_Last_Name_1": "Rawls",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "Laurel Leaf Books",
"Owned": "yes",
"Favorite": "no",
"Completed": "yes",
"Currently_Reading": "no",
"Personal_Or_Academic": "personal",
"Genre_1": "fiction",
"Genre_2": "novel"}

# Book 6
{"ISBN": "9780062560308",
"Title": "Under a Dark Sky",
"Publish_Year": "2018",
"Summary": "",
"Chapters": "40",
"Chapters_Completed": "40",
"Cover_Image": "",
"Author_First_Name_1": "Lori",
"Author_Last_Name_1": "Rader-Day",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "William Morrow",
"Owned": "yes",
"Favorite": "no",
"Completed": "yes",
"Currently_Reading": "no",
"Personal_Or_Academic": "personal",
"Genre_1": "fiction",
"Genre_2": "novel",
"Genre_3": "mystery"}

# Book 7
{"ISBN": "0345342968",
"Title": "Fahrenheit 451",
"Publish_Year": "1953",
"Summary": "",
"Chapters": "",
"Chapters_Completed": "",
"Cover_Image": "",
"Author_First_Name_1": "Ray",
"Author_Last_Name_1": "Bradbury",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "Del Rey Books",
"Owned": "yes",
"Favorite": "yes",
"Completed": "yes",
"Currently_Reading": "no",
"Personal_Or_Academic": "personal",
"Genre_1": "fiction",
"Genre_2": "novel",
"Genre_3": "dystopian"}

# Book 8
{"ISBN": "0345347536",
"Title": "A Spell For Chameleon",
"Publish_Year": "1977",
"Summary": "Everyone has a magic talent, except for Bink.",
"Chapters": "16",
"Chapters_Completed": "16",
"Cover_Image": "",
"Author_First_Name_1": "Piers",
"Author_Last_Name_1": "Anthony",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "Del Rey Books",
"Owned": "yes",
"Favorite": "yes",
"Completed": "yes",
"Currently_Reading": "no",
"Personal_Or_Academic": "personal",
"Genre_1": "fiction",
"Genre_2": "fantasy"}

# Book 9
{"ISBN": "0345350588",
"Title": "The Source of Magic",
"Publish_Year": "1979",
"Summary": "Where Xanth gets its magic from.",
"Chapters": "14",
"Chapters_Completed": "14",
"Cover_Image": "",
"Author_First_Name_1": "Piers",
"Author_Last_Name_1": "Anthony",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "Del Rey Books",
"Owned": "yes",
"Favorite": "no",
"Completed": "yes",
"Currently_Reading": "no",
"Personal_Or_Academic": "personal",
"Genre_1": "fiction",
"Genre_2": "fantasy"}


# Book 10
{"ISBN": "0451524934",
"Title": "1984",
"Publish_Year": "1950",
"Summary": "",
"Chapters": "",
"Chapters_Completed": "",
"Cover_Image": "",
"Author_First_Name_1": "George",
"Author_Last_Name_1": "Orwell",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "Signet Classic",
"Owned": "yes",
"Favorite": "no",
"Completed": "yes",
"Currently_Reading": "no",
"Personal_Or_Academic": "personal",
"Genre_1": "fiction",
"Genre_2": "novel",
"Genre_3": "dystopian"}

# Book 11
{"ISBN": "0671023373",
"Title": "Man's Search For Meaning",
"Publish_Year": "1946",
"Summary": "",
"Chapters": "",
"Chapters_Completed": "",
"Cover_Image": "",
"Author_First_Name_1": "Viktor E.",
"Author_Last_Name_1": "Frankl",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "Pocket Books",
"Owned": "yes",
"Favorite": "yes",
"Completed": "yes",
"Currently_Reading": "no",
"Personal_Or_Academic": "personal",
"Genre_1": "nonfiction",
"Genre_2": "novel"}

# Book 12
{"ISBN": "0156027348",
"Title": "Odd Girl Out",
"Publish_Year": "2002",
"Summary": "",
"Chapters": "9",
"Chapters_Completed": "9",
"Cover_Image": "",
"Author_First_Name_1": "Rachel",
"Author_Last_Name_1": "Simmons",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "Harcourt",
"Owned": "yes",
"Favorite": "no",
"Completed": "yes",
"Currently_Reading": "no",
"Personal_Or_Academic": "academic",
"Genre_1": "nonfiction",
"Genre_2": "psychology"}

# Book 13
{"ISBN": "0072920491",
"Title": "Personality Psychology",
"Publish_Year": "2005",
"Summary": "Domains of knowledge about human nature.",
"Chapters": "",
"Chapters_Completed": "",
"Cover_Image": "",
"Author_First_Name_1": "Randy",
"Author_Last_Name_1": "Larsen",
"Author_First_Name_2": "David",
"Author_Last_Name_2": "Buss",
"Publisher_Name": "McGraw-Hill",
"Owned": "yes",
"Favorite": "no",
"Completed": "no",
"Currently_Reading": "no",
"Personal_Or_Academic": "academic",
"Genre_1": "nonfiction",
"Genre_2": "psychology"}

# Book 14
{"ISBN": "0072920491",
"Title": "Sensation and Perception",
"Publish_Year": "2005",
"Summary": "",
"Chapters": "",
"Chapters_Completed": "",
"Cover_Image": "",
"Author_First_Name_1": "E. Bruce",
"Author_Last_Name_1": "Goldstein",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "Wadsworth",
"Owned": "yes",
"Favorite": "no",
"Completed": "no",
"Currently_Reading": "no",
"Personal_Or_Academic": "academic",
"Genre_1": "nonfiction",
"Genre_2": "psychology",
"Genre_3": "science"}

# Book 15
{"ISBN": "9780064410342",
"Title": "Howl's Moving Castle",
"Publish_Year": "2001",
"Summary": "",
"Chapters": "21",
"Chapters_Completed": "9",
"Cover_Image": "",
"Author_First_Name_1": "Diana Wynne",
"Author_Last_Name_1": "Jones",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
"Publisher_Name": "Harper Trophy",
"Owned": "yes",
"Favorite": "yes",
"Completed": "yes",
"Currently_Reading": "yes",
"Personal_Or_Academic": "personal",
"Genre_1": "fiction",
"Genre_2": "novel",
"Genre_3": "fantasy"}