# Sample Books

# Book 1
{*"ISBN": "9780593158203",
 *"Title": "A Game of Thrones",
*"Publish_Year": "2019",
"Summary": "Not required",
"Chapters": "73",
"Chapters_Completed": "20",
"Cover_Image": "",
*"Author_First_Name_1": "George R. R.",
*"Author_Last_Name_1": "Martin",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
*"Publisher_Name": "Bantam Books",
*"Owned": "yes",
*"Favorite": "no",
*"Completed": "no",
*"Currently_Reading": "Yes",
*"Personal_Or_Academic": "personal",
*"Genre_1": "fiction",
"Genre_2": "fantasy"
"Genre_3": "adventure"}

# Book 2
{*"ISBN": "9781607317326",
 *"Title": "30 Under 30: Young Adults in Scripture Who Heard from God",
*"Publish_Year": "2025",
"Summary": "Not required",
"Chapters": "6",
"Chapters_Completed": "6",
"Cover_Image": "",
*"Author_First_Name_1": "Josh",
*"Author_Last_Name_1": "Wellborn",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
*"Publisher_Name": "Gospel Publishing House",
*"Owned": "yes",
*"Favorite": "Yes",
*"Completed": "Yes",
*"Currently_Reading": "no",
*"Personal_Or_Academic": "personal",
*"Genre_1": "non-fiction",
"Genre_2": "devotional"}

# Book 3
{*"ISBN": "0812974611",
 *"Title": "Pompeii",
*"Publish_Year": "2005",
"Summary": "Not required",
"Chapters": "21",
"Chapters_Completed": "0",
"Cover_Image": "",
*"Author_First_Name_1": "Robert",
*"Author_Last_Name_1": "Harris",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
*"Publisher_Name": "Random House Trade Paperbacks",
*"Owned": "yes",
*"Favorite": "no",
*"Completed": "no",
*"Currently_Reading": "no",
*"Personal_Or_Academic": "personal",
*"Genre_1": "fiction",
"Genre_2": "mystery"}

# Book 4
{*"ISBN": "9781452102276",
 *"Title": "Star Wars: The Jedi Path",
*"Publish_Year": "2011",
"Summary": "Not required",
"Chapters": "4",
"Chapters_Completed": "4",
"Cover_Image": "",
*"Author_First_Name_1": "Daniel",
*"Author_Last_Name_1": "Wallace",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
*"Publisher_Name": "Chronicle Books",
*"Owned": "yes",
*"Favorite": "no",
*"Completed": "yes",
*"Currently_Reading": "no",
*"Personal_Or_Academic": "personal",
*"Genre_1": "fiction",
"Genre_2": "Sci-Fi"}

# Book 5
{*"ISBN": "9781503943377",
 *"Title": "Beneath a Scarlet Sky",
*"Publish_Year": "2017",
"Summary": "Not required",
"Chapters": "34",
"Chapters_Completed": "1",
"Cover_Image": "",
*"Author_First_Name_1": "Mark",
*"Author_Last_Name_1": "Sullivan",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
*"Publisher_Name": "Lake Union Publishing",
*"Owned": "yes",
*"Favorite": "no",
*"Completed": "no",
*"Currently_Reading": "yes",
*"Personal_Or_Academic": "personal",
*"Genre_1": "fiction",
"Genre_2": "history"}

# Book 6
{*"ISBN": "9780801094927",
 *"Title": "Welcome to Adulting",
*"Publish_Year": "2018",
"Summary": "Not required",
"Chapters": "42",
"Chapters_Completed": "0",
"Cover_Image": "",
*"Author_First_Name_1": "Jonathan",
*"Author_Last_Name_1": "Pokluda",
"Author_First_Name_2": "Kevin",
"Author_Last_Name_2": "McConaghy",
*"Publisher_Name": "Baker Books",
*"Owned": "yes",
*"Favorite": "no",
*"Completed": "no",
*"Currently_Reading": "no",
*"Personal_Or_Academic": "personal",
*"Genre_1": "non-fiction",
"Genre_2": "Christian Living"}

# Book 7
{*"ISBN": "9781496213297",
 *"Title": "When the Crowd Didn't Roar",
*"Publish_Year": "2019",
"Summary": "Not required",
"Chapters": "0",
"Chapters_Completed": "0",
"Cover_Image": "",
*"Author_First_Name_1": "Kevin",
*"Author_Last_Name_1": "Cowherd",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
*"Publisher_Name": "University of Nebraska Press",
*"Owned": "yes",
*"Favorite": "no",
*"Completed": "no",
*"Currently_Reading": "yes",
*"Personal_Or_Academic": "personal",
*"Genre_1": "non-fiction",
"Genre_2": "history"}

# Book 8
{*"ISBN": "9780871404237",
 *"Title": "SPQR",
*"Publish_Year": "2016",
"Summary": "Not required",
"Chapters": "12",
"Chapters_Completed": "12",
"Cover_Image": "",
*"Author_First_Name_1": "Mary",
*"Author_Last_Name_1": "Beard",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
*"Publisher_Name": "Liveright Publishing Corporation, Liveright",
*"Owned": "yes",
*"Favorite": "yes",
*"Completed": "yes",
*"Currently_Reading": "no",
*"Personal_Or_Academic": "personal",
*"Genre_1": "non-fiction",
"Genre_2": "history"}

# Book 9
{*"ISBN": "9781635266597",
 *"Title": "Learning SAS by Example",
*"Publish_Year": "2018",
"Summary": "Not required",
"Chapters": "27",
"Chapters_Completed": "27",
"Cover_Image": "",
*"Author_First_Name_1": "Ron",
*"Author_Last_Name_1": "Cody",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
*"Publisher_Name": "SAS Institute",
*"Owned": "yes",
*"Favorite": "no",
*"Completed": "yes",
*"Currently_Reading": "no",
*"Personal_Or_Academic": "academic",
*"Genre_1": "non-fiction",
"Genre_2": "computer programming"}

# Book 10
{*"ISBN": "9781909245648",
 *"Title": "Faith of Our Families : Everton FC an Oral History",
*"Publish_Year": "2018",
"Summary": "Not required",
"Chapters": "2",
"Chapters_Completed": "2",
"Cover_Image": "",
*"Author_First_Name_1": "James",
*"Author_Last_Name_1": "Corbett",
"Author_First_Name_2": "",
"Author_Last_Name_2": "",
*"Publisher_Name": "deCoubertin Books",
*"Owned": "yes",
*"Favorite": "yes",
*"Completed": "yes",
*"Currently_Reading": "no",
*"Personal_Or_Academic": "personal",
*"Genre_1": "non-fiction",
"Genre_2": "history"}
