-- SQL INSERT statements for Genre table
-- Generated from dewey_Dec_Tbl.csv

INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (100, 'Philosophy & psychology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (110, 'Metaphysics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (120, 'Epistemology, causation, humankind');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (130, 'Paranormal phenomena');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (140, 'Philosophical schools of thought');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (150, 'Psychology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (160, 'Logic');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (170, 'Ethics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (180, 'Ancient, medieval & Eastern philosophy');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (190, 'Modern Western philosophy');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (200, 'Religion');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (210, 'Philosophy & theory of religion');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (220, 'The Bible');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (230, 'Christianity & Christian theology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (240, 'Christian moral & devotional theology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (250, 'Christian orders & local church');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (260, 'Christian social & ecclesiastical theology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (270, 'History of Christianity');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (280, 'Christian denominations');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (290, 'Other religions');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (300, 'Social sciences');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (310, 'Statistics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (320, 'Political science');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (330, 'Economics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (340, 'Law');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (350, 'Public administration & military science');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (360, 'Social problems & services');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (370, 'Education');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (380, 'Commerce, communications, transportation');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (390, 'Customs, etiquette, folklore');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (400, 'Language');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (410, 'Linguistics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (420, 'English & Old English languages');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (430, 'Germanic languages');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (440, 'Romance languages (French, etc.)');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (450, 'Italian, Romanian, related languages');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (460, 'Spanish & Portuguese');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (470, 'Latin');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (480, 'Classical Greek');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (490, 'Other languages');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (500, 'Science');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (510, 'Mathematics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (520, 'Astronomy');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (530, 'Physics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (540, 'Chemistry');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (550, 'Earth sciences & geology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (560, 'Fossils & prehistoric life');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (570, 'Life sciences');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (580, 'Plants (botany)');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (590, 'Animals (zoology)');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (600, 'Technology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (610, 'Medicine & health');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (620, 'Engineering');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (630, 'Agriculture');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (640, 'Home & family management');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (650, 'Management & public relations');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (660, 'Chemical engineering');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (670, 'Manufacturing');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (680, 'Manufacture for specific uses');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (690, 'Construction');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (700, 'Arts & recreation');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (710, 'Civic & landscape art');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (720, 'Architecture');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (730, 'Sculpture, ceramics, metalwork');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (740, 'Drawing & decorative arts');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (750, 'Painting');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (760, 'Printmaking & prints');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (770, 'Photography');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (780, 'Music');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (790, 'Sports, games & entertainment');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (800, 'Literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (810, 'American literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (820, 'English literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (830, 'German literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (840, 'French literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (850, 'Italian literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (860, 'Spanish & Portuguese literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (870, 'Latin literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (880, 'Classical Greek literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (890, 'Other literatures');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (900, 'History & geography');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (910, 'Geography & travel');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (920, 'Biography & genealogy');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (930, 'Ancient world history');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (940, 'Europe');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (950, 'Asia');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (960, 'Africa');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (970, 'North America');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (980, 'South America');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (990, 'Other areas');

-- Total records inserted: 90
