-- SQL INSERT statements for Genre table
-- Generated from dewey_Dec_Tbl.csv

INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (100, 'philosophy psychology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (110, 'metaphysics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (120, 'epistemology causation humankind');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (130, 'paranormal phenomena');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (140, 'philosophical schools thought');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (150, 'psychology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (160, 'logic');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (170, 'ethics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (180, 'ancient medieval eastern philosophy');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (190, 'modern western philosophy');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (200, 'religion');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (210, 'philosophy theory religion');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (220, 'the bible');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (230, 'christianity christian theology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (240, 'christian moral devotional theology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (250, 'christian orders local church');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (260, 'christian social ecclesiastical theology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (270, 'history christianity');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (280, 'christian denominations');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (290, 'other religions');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (300, 'social sciences');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (310, 'statistics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (320, 'political science');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (330, 'economics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (340, 'law');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (350, 'public administration military science');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (360, 'social problems services');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (370, 'education');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (380, 'commerce communications transportation');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (390, 'customs etiquette folklore');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (400, 'language');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (410, 'linguistics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (420, 'english old english languages');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (430, 'germanic languages');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (440, 'romance languages french etc');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (450, 'italian romanian related languages');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (460, 'spanish portuguese');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (470, 'latin');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (480, 'classical greek');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (490, 'other languages');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (500, 'science');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (510, 'mathematics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (520, 'astronomy');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (530, 'physics');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (540, 'chemistry');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (550, 'earth sciences geology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (560, 'fossils prehistoric life');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (570, 'life sciences');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (580, 'plants botany');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (590, 'animals zoology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (600, 'technology');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (610, 'medicine health');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (620, 'engineering');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (630, 'agriculture');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (640, 'home family management');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (650, 'management public relations');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (660, 'chemical engineering');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (670, 'manufacturing');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (680, 'manufacture specific uses');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (690, 'construction');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (700, 'arts recreation');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (710, 'civic landscape art');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (720, 'architecture');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (730, 'sculpture ceramics metalwork');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (740, 'drawing decorative arts');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (750, 'painting');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (760, 'printmaking prints');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (770, 'photography');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (780, 'music');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (790, 'sports games entertainment');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (800, 'literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (810, 'american literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (820, 'english literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (830, 'german literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (840, 'french literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (850, 'italian literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (860, 'spanish portuguese literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (870, 'latin literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (880, 'classical greek literature');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (890, 'other literatures');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (900, 'history geography');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (910, 'geography travel');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (920, 'biography genealogy');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (930, 'ancient world history');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (940, 'europe');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (950, 'asia');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (960, 'africa');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (970, 'north america');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (980, 'south america');
INSERT INTO DD_Sys (Class_Num, Class_Desc) VALUES (990, 'other areas');