from app.services.Book.Book import create_book


def create_sample_books():
    for book in books:
        create_book(book)


books = ({"ISBN": "0312278497",
          "Title": "The Glass Bead Game",
          "Publish_Year": "1970",
          "Summary": "The state of Castalia is the home of an austere order of intellectuals.",
          "Chapters": "23",
          "Chapters_Completed": "2",
          "Cover_Image": "",
          "Author_First_Name_1": "Herman",
          "Author_Last_Name_1": "Hesse",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Picador",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "fantasy"},

         {"ISBN": "9781405964098",
          "Title": "Of Mice and Men",
          "Publish_Year": "1937",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "John",
          "Author_Last_Name_1": "Steinbeck",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Penguin Books",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "literature"},

         {"ISBN": "9781803366531",
          "Title": "Reformatory",
          "Publish_Year": "2023",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Tananarive",
          "Author_Last_Name_1": "Due",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Titan Books Limited",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "horror"},

         {"ISBN": "006091307X",
          "Title": "The Crying of Lot 49",
          "Publish_Year": "1965",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Thomas",
          "Author_Last_Name_1": "Pynchon",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Harper Perennial Modern Classics",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "literature"},

{"ISBN": "0744586534",
          "Title": "Dracula",
          "Publish_Year": "1897",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Bram",
          "Author_Last_Name_1": "Stoker",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Walker",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "horror"},

         {"ISBN": "0099475014",
          "Title": "The Sound and the Fury",
          "Publish_Year": "1929",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "William",
          "Author_Last_Name_1": "Faulkner",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Vintage",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "literature"},

         {"ISBN": "0061002828",
          "Title": "The Hellbound Heart",
          "Publish_Year": "1991",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Clive",
          "Author_Last_Name_1": "Barker",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "HarperTorch",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "horror"},

         {"ISBN": "0061091464",
          "Title": "The Thief of Always",
          "Publish_Year": "1993",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Clive",
          "Author_Last_Name_1": "Barker",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "HarperCollins",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "horror"},

         {"ISBN": "9781407135397",
          "Title": "The Hunger Games",
          "Publish_Year": "2008",
          "Summary": "",
          "Chapters": "0",
          "Chapters_Completed": "24",
          "Cover_Image": "",
          "Author_First_Name_1": "Suzanne",
          "Author_Last_Name_1": "Collins",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Scholastic",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "science fiction",
          "Genre_3": "dystopian",
          "Genre_4": "children"},

         {"ISBN": "1529370515",
          "Title": "The Stand",
          "Publish_Year": "1992",
          "Summary": "One man escapes from a biological weapon facility after an accident, carrying with "
                     "him the deadly virus known as Captain Tripps.",
          "Chapters": "50",
          "Chapters_Completed": "50",
          "Cover_Image": "",
          "Author_First_Name_1": "Stephen",
          "Author_Last_Name_1": "King",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Hodder",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "horror"},

         {"ISBN": "9780425037843",
          "Title": "Pale Fire",
          "Publish_Year": "1977",
          "Summary": "A 999 line poem in heroic couplets, divided into 4 cantos, was composed--according "
                     "to Nabokov's fiction--by John Francis Shade, an obsessively methodical man, during "
                     "the last 20 days of his life. ",
          "Chapters": "3",
          "Chapters_Completed": "2",
          "Cover_Image": "",
          "Author_First_Name_1": "Vladimir",
          "Author_Last_Name_1": "Nabokov",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Berkley",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "no",
          "Currently_Reading": "yes",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "literature"},

         {"ISBN": "9780425127933",
          "Title": "The Damnation Game",
          "Publish_Year": "1985",
          "Summary": "",
          "Chapters": "30",
          "Chapters_Completed": "20",
          "Cover_Image": "",
          "Author_First_Name_1": "Clive",
          "Author_Last_Name_1": "Barker",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Berkley",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "horror"},

         {"ISBN": "9780201835953",
          "Title": "The Mythical Man-Month",
          "Publish_Year": "1975",
          "Summary": "",
          "Chapters": "30",
          "Chapters_Completed": "20",
          "Cover_Image": "",
          "Author_First_Name_1": "Frederick",
          "Author_Last_Name_1": "Brooks",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Addison-Wesley Professional",
          "Owned": "no",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "academic",
          "Genre_1": "nonfiction",
          "Genre_2": "programming"},

         {"ISBN": "0201485370",
          "Title": "Design patterns",
          "Publish_Year": "1995",
          "Summary": "",
          "Chapters": "30",
          "Chapters_Completed": "0",
          "Cover_Image": "",
          "Author_First_Name_1": "Erich",
          "Author_Last_Name_1": "Gamma",
          "Author_First_Name_2": "Richard",
          "Author_Last_Name_2": "Helm",
          "Publisher_Name": "Addison-Wesley Professional",
          "Owned": "no",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "academic",
          "Genre_1": "nonfiction",
          "Genre_2": "programming"},

         {"ISBN": "0201485370",
          "Title": "Harry Potter and the Sorcerer's Stone",
          "Publish_Year": "1997",
          "Summary": "",
          "Chapters": "30",
          "Chapters_Completed": "0",
          "Cover_Image": "",
          "Author_First_Name_1": "J.K.",
          "Author_Last_Name_1": "Rowling",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Scholastic ",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "fantasy"},

         {"ISBN": "9780345368935",
          "Title": "All The Weyrs Of Pern",
          "Publish_Year": "1991",
          "Summary": "The end of Thread.",
          "Chapters": "20",
          "Chapters_Completed": "20",
          "Cover_Image": "",
          "Author_First_Name_1": "Anne",
          "Author_Last_Name_1": "McCaffrey",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Del Rey Books",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "fantasy",
          "Genre_3": "science fiction"},

         {"ISBN": "0345434692",
          "Title": "The Skies Of Pern",
          "Publish_Year": "2001",
          "Summary": "The last book of the Dragonriders of Pern series.",
          "Chapters": "4",
          "Chapters_Completed": "4",
          "Cover_Image": "",
          "Author_First_Name_1": "Anne",
          "Author_Last_Name_1": "McCaffrey",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Del Rey Books",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "fantasy",
          "Genre_3": "science fiction"},

         {"ISBN": "9780345484260",
          "Title": "Dragonflight",
          "Publish_Year": "2005",
          "Summary": "The first book of the Dragonriders of Pern series.",
          "Chapters": "4",
          "Chapters_Completed": "4",
          "Cover_Image": "",
          "Author_First_Name_1": "Anne",
          "Author_Last_Name_1": "McCaffrey",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Del Rey Books",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "fantasy",
          "Genre_3": "science fiction"},

         {"ISBN": "0764568825",
          "Title": "Taming the Flame",
          "Publish_Year": "2005",
          "Summary": "Secrets for Hot-and-Quick Grilling and Low-and-Slow BBQ",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Elizabeth",
          "Author_Last_Name_1": "Karmel",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Wiley Publishing Inc",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "nonfiction",
          "Genre_2": "cookbook"},

         {"ISBN": "0553274295",
          "Title": "Where The Red Fern Grows",
          "Publish_Year": "2001",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Wilson",
          "Author_Last_Name_1": "Rawls",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Laurel Leaf Books",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "novel"},

         {"ISBN": "9780062560308",
          "Title": "Under a Dark Sky",
          "Publish_Year": "2018",
          "Summary": "",
          "Chapters": "40",
          "Chapters_Completed": "40",
          "Cover_Image": "",
          "Author_First_Name_1": "Lori",
          "Author_Last_Name_1": "Rader-Day",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "William Morrow",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "novel",
          "Genre_3": "mystery"},

         {"ISBN": "0345342968",
          "Title": "Fahrenheit 451",
          "Publish_Year": "1953",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Ray",
          "Author_Last_Name_1": "Bradbury",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Del Rey Books",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "novel",
          "Genre_3": "dystopian"},

         {"ISBN": "0345347536",
          "Title": "A Spell For Chameleon",
          "Publish_Year": "1977",
          "Summary": "Everyone has a magic talent, except for Bink.",
          "Chapters": "16",
          "Chapters_Completed": "16",
          "Cover_Image": "",
          "Author_First_Name_1": "Piers",
          "Author_Last_Name_1": "Anthony",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Del Rey Books",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "fantasy"},

         {"ISBN": "0345350588",
          "Title": "The Source of Magic",
          "Publish_Year": "1979",
          "Summary": "Where Xanth gets its magic from.",
          "Chapters": "14",
          "Chapters_Completed": "14",
          "Cover_Image": "",
          "Author_First_Name_1": "Piers",
          "Author_Last_Name_1": "Anthony",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Del Rey Books",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "fantasy"},

         {"ISBN": "0451524934",
          "Title": "1984",
          "Publish_Year": "1950",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "George",
          "Author_Last_Name_1": "Orwell",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Signet Classic",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "novel",
          "Genre_3": "dystopian"},

         {"ISBN": "0671023373",
          "Title": "Man's Search For Meaning",
          "Publish_Year": "1946",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Viktor E.",
          "Author_Last_Name_1": "Frankl",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Pocket Books",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "nonfiction",
          "Genre_2": "novel"},

         {"ISBN": "0156027348",
          "Title": "Odd Girl Out",
          "Publish_Year": "2002",
          "Summary": "",
          "Chapters": "9",
          "Chapters_Completed": "9",
          "Cover_Image": "",
          "Author_First_Name_1": "Rachel",
          "Author_Last_Name_1": "Simmons",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Harcourt",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "academic",
          "Genre_1": "nonfiction",
          "Genre_2": "psychology"},

         {"ISBN": "0072920491",
          "Title": "Personality Psychology",
          "Publish_Year": "2005",
          "Summary": "Domains of knowledge about human nature.",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Randy",
          "Author_Last_Name_1": "Larsen",
          "Author_First_Name_2": "David",
          "Author_Last_Name_2": "Buss",
          "Publisher_Name": "McGraw-Hill",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "academic",
          "Genre_1": "nonfiction",
          "Genre_2": "psychology"},

         {"ISBN": "0072920491",
          "Title": "Sensation and Perception",
          "Publish_Year": "2005",
          "Summary": "",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "E. Bruce",
          "Author_Last_Name_1": "Goldstein",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Wadsworth",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "academic",
          "Genre_1": "nonfiction",
          "Genre_2": "psychology",
          "Genre_3": "science"},

         {"ISBN": "9780064410342",
          "Title": "Howl's Moving Castle",
          "Publish_Year": "2001",
          "Summary": "",
          "Chapters": "21",
          "Chapters_Completed": "9",
          "Cover_Image": "",
          "Author_First_Name_1": "Diana Wynne",
          "Author_Last_Name_1": "Jones",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Harper Trophy",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "yes",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "novel",
          "Genre_3": "fantasy"},

         {"ISBN": "9780593158203",
          "Title": "A Game of Thrones",
          "Publish_Year": "2019",
          "Summary": "",
          "Chapters": "73",
          "Chapters_Completed": "20",
          "Cover_Image": "",
          "Author_First_Name_1": "George R. R.",
          "Author_Last_Name_1": "Martin",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Bantam Books",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "Yes",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "fantasy",
          "Genre_3": "adventure"},

         {"ISBN": "9781607317326",
          "Title": "30 Under 30: Young Adults in Scripture Who Heard from God",
          "Publish_Year": "2025",
          "Summary": "",
          "Chapters": "6",
          "Chapters_Completed": "6",
          "Cover_Image": "",
          "Author_First_Name_1": "Josh",
          "Author_Last_Name_1": "Wellborn",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Gospel Publishing House",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "non-fiction",
          "Genre_2": "religion"},

         {"ISBN": "0812974611",
          "Title": "Pompeii",
          "Publish_Year": "2005",
          "Summary": "",
          "Chapters": "21",
          "Chapters_Completed": "0",
          "Cover_Image": "",
          "Author_First_Name_1": "Robert",
          "Author_Last_Name_1": "Harris",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Random House Trade Paperbacks",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "mystery"},

         {"ISBN": "9781452102276",
          "Title": "Star Wars: The Jedi Path",
          "Publish_Year": "2011",
          "Summary": "",
          "Chapters": "4",
          "Chapters_Completed": "4",
          "Cover_Image": "",
          "Author_First_Name_1": "Daniel",
          "Author_Last_Name_1": "Wallace",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Chronicle Books",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "sci-fi"},

         {"ISBN": "9781503943377",
          "Title": "Beneath a Scarlet Sky",
          "Publish_Year": "2017",
          "Summary": "",
          "Chapters": "34",
          "Chapters_Completed": "1",
          "Cover_Image": "",
          "Author_First_Name_1": "Mark",
          "Author_Last_Name_1": "Sullivan",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Lake Union Publishing",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "yes",
          "Personal_Or_Academic": "personal",
          "Genre_1": "fiction",
          "Genre_2": "history"},

         {"ISBN": "9780801094927",
          "Title": "Welcome to Adulting",
          "Publish_Year": "2018",
          "Summary": "",
          "Chapters": "42",
          "Chapters_Completed": "0",
          "Cover_Image": "",
          "Author_First_Name_1": "Jonathan",
          "Author_Last_Name_1": "Pokluda",
          "Author_First_Name_2": "Kevin",
          "Author_Last_Name_2": "McConaghy",
          "Publisher_Name": "Baker Books",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "non-fiction",
          "Genre_2": "religion",
          "Genre_3": "wellness"},

         {"ISBN": "9781496213297",
          "Title": "When the Crowd Didn't Roar",
          "Publish_Year": "2019",
          "Summary": "",
          "Chapters": "0",
          "Chapters_Completed": "0",
          "Cover_Image": "",
          "Author_First_Name_1": "Kevin",
          "Author_Last_Name_1": "Cowherd",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "University of Nebraska Press",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "yes",
          "Personal_Or_Academic": "personal",
          "Genre_1": "non-fiction",
          "Genre_2": "history"},

         {"ISBN": "9780871404237",
          "Title": "SPQR",
          "Publish_Year": "2016",
          "Summary": "",
          "Chapters": "12",
          "Chapters_Completed": "12",
          "Cover_Image": "",
          "Author_First_Name_1": "Mary",
          "Author_Last_Name_1": "Beard",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Liveright Publishing Corporation, Liveright",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "non-fiction",
          "Genre_2": "history"},

         {"ISBN": "9781635266597",
          "Title": "Learning SAS by Example",
          "Publish_Year": "2018",
          "Summary": "",
          "Chapters": "27",
          "Chapters_Completed": "27",
          "Cover_Image": "",
          "Author_First_Name_1": "Ron",
          "Author_Last_Name_1": "Cody",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "SAS Institute",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "academic",
          "Genre_1": "non-fiction",
          "Genre_2": "programming"},

         {"ISBN": "9781909245648",
          "Title": "Faith of Our Families : Everton FC an Oral History",
          "Publish_Year": "2018",
          "Summary": "Not required",
          "Chapters": "2",
          "Chapters_Completed": "2",
          "Cover_Image": "",
          "Author_First_Name_1": "James",
          "Author_Last_Name_1": "Corbett",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "deCoubertin Books",
          "Owned": "yes",
          "Favorite": "yes",
          "Completed": "yes",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "non-fiction",
          "Genre_2": "history"},

         {"ISBN": "0749397055",
          "Title": "The Name of the Rose",
          "Publish_Year": "1922",
          "Summary": "It is the year 1327. Franciscans in an Italian abbey are suspected of heresy, "
                     "but Brother William of Baskerville’s investigation is suddenly overshadowed by seven "
                     "bizarre deaths.",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Umberto",
          "Author_Last_Name_1": "Enco",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Secker & Warburg",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "history",
          "Genre_2": "mystery"},

         {"ISBN": "0553840010",
          "Title": "The Alienist",
          "Publish_Year": "1995",
          "Summary": "The year is 1896, the place, New York City. On a cold March night New York Times reporter "
                     "John Schuyler Moore is summoned to the East River by his friend and former Harvard classmate "
                     "Dr. Laszlo Kreizler, a psychologist, or alienist. On the unfinished Williamsburg Bridge, "
                     "they view the horribly mutilated body of an adolescent boy, a prostitute from one of "
                     "Manhattan's infamous brothels. The newly appointed police commissioner",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Caleb",
          "Author_Last_Name_1": "Carr",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Brantom Books",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "history",
          "Genre_2": "mystery"},

         {"ISBN": "1841979120",
          "Title": "Dissolution",
          "Publish_Year": "2003",
          "Summary": "Dissolution follows lawyer‑monk Matthew Shardlake as he investigates a brutal murder at a "
                     "monastery during Henry VIII’s dissolution of the religious houses, uncovering corruption, "
                     "fear, and political intrigue. His search for the killer forces him to confront the moral "
                     "collapse of the era and the cost of loyalty in a world reshaped by power.",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "C.J.",
          "Author_Last_Name_1": "Sansom",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "W.F.Howes",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "history",
          "Genre_2": "mystery"},

         {"ISBN": "9780749008529",
          "Title": "The Beekeeper's Apprentice",
          "Publish_Year": "2017",
          "Summary": "In 1915, Sherlock Holmes is retired and quietly engaged in the study of honeybees "
                     "in Sussex when a young woman literally stumbles onto him on the Sussex Downs.",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Laurie",
          "Author_Last_Name_1": "King",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Allison & Busby",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "mystery",
          "Genre_2": "history"},

         {"ISBN": "753826852",
          "Title": "The Shadow of the Wind",
          "Publish_Year": "2009",
          "Summary": "Hidden in the heart of the old city of Barcelona is the 'Cemetery of Forgotten Books', a "
                     "labyrinthine library of obscure and forgotten titles. To this library, a man brings his "
                     "ten-year-old son, Daniel, one cold morning in 1945.",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Carlos",
          "Author_Last_Name_1": "Zafon",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Phoenix",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "mystery",
          "Genre_2": "history"},

         {"ISBN": "1423108752",
          "Title": "Uncharted: a Gates family mystery",
          "Publish_Year": "2008",
          "Summary": "Follows teenage siblings Nick and Maddie Gates as they uncover a hidden map left by "
                     "their ancestors, pulling them into a centuries‑old puzzle tied to American history. "
                     "Their hunt for the truth forces them to outsmart rivals and confront the legacy of the "
                     "Gates family’s long connection to secret treasures.",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Cathy",
          "Author_Last_Name_1": "Hapka",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Disney Press (Hyperion)",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "mystery",
          "Genre_2": "history"},

         {"ISBN": "9781585478927",
          "Title": "The Thirteenth Tale (Readers Circle (Center Point))",
          "Publish_Year": "2007",
          "Summary": "Who summons a young biographer to hear the true, haunting story of her childhood "
                     "after a lifetime of fabrications. As the biographer uncovers the dark secrets of the "
                     "Angelfield family, both women are forced to confront the ghosts—literal and emotional—that "
                     "have shaped their lives.",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Diane",
          "Author_Last_Name_1": "Setterfield",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Center Point Large Print",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "mystery",
          "Genre_2": "history"},

         {"ISBN": "054774501X",
          "Title": "The Hangman's Daughter",
          "Publish_Year": "2011",
          "Summary": "Germany, 1659: When a dying boy is pulled from the river with a mark crudely "
                     "tattooed on his shoulder, hangman Jakob Kuisl is called upon to investigate whether "
                     "witchcraft is at play in his small Bavarian town. Whispers and dark memories of witch trials "
                     "and the women burned at stake just seventy years earlier still haunt the streets of Schongau.",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Oliver",
          "Author_Last_Name_1": "Potzsch",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Houghton Mifflin Harcourt",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "mystery",
          "Genre_2": "history"},

         {"ISBN": "0062879723",
          "Title": "The ABC Murders",
          "Publish_Year": "1936",
          "Summary": "There's a serial killer on the loose, bent on working his way though the alphabet. "
                     "There seems little chance of the murderer being caught - until her makes the crucial "
                     "and vain mistake of challenging Hercule Poirot to frustrate his plans . . .",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Agatha",
          "Author_Last_Name_1": "Christie",
          "Author_First_Name_2": "",
          "Author_Last_Name_2": "",
          "Publisher_Name": "Dodd, Meod & Co.",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "mystery",
          "Genre_2": "history"},

         {"ISBN": "1401891551",
          "Title": "Introduction to Health Care",
          "Publish_Year": "2006",
          "Summary": "Understand the different options when it comes to care.  Primary/Emergency/Specialist/!Satellite!",
          "Chapters": "",
          "Chapters_Completed": "",
          "Cover_Image": "",
          "Author_First_Name_1": "Joyce",
          "Author_Last_Name_1": "Mitchell",
          "Author_First_Name_2": "Lee",
          "Author_Last_Name_2": "Haroun",
          "Publisher_Name": "Cengage Delmar Learning",
          "Owned": "yes",
          "Favorite": "no",
          "Completed": "no",
          "Currently_Reading": "no",
          "Personal_Or_Academic": "personal",
          "Genre_1": "mystery",
          "Genre_2": "history"}

         )

if __name__ == '__main__':
    pass
